name: Run with shared environment variables
description: Sources runtime.env then runs a command with that environment
inputs:
  cmd:
    description: "Command to run with sourced env"
    required: true

runs:
  using: "composite"
  steps:
    - name: Make entrypoint executable
      shell: bash
      run: chmod +x ${{ github.action_path }}/entrypoint.sh

    - name: Run command with shared env
      shell: bash
      run: ${{ github.action_path }}/entrypoint.sh "${{ inputs.cmd }}"
