name: Setup Tools
description: Install helm, kubectl, jq, yq, and Oracle CLI locally
runs:
  using: "composite"
  steps:
    - name: Create tools directory
      shell: bash 
      run: |
        mkdir -p "${GITHUB_WORKSPACE}/tools/bin"
        echo "export PATH=${PATH}:${GITHUB_WORKSPACE}/tools/bin" > "${GITHUB_WORKSPACE}/runtime.env"

    - name: Install kubectl
      shell: bash 
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        mv kubectl "${GITHUB_WORKSPACE}/tools/bin/kubectl"

    - name: Install helm
      shell: bash 
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        mv /usr/local/bin/helm "${GITHUB_WORKSPACE}/tools/bin/helm"

    - name: Install jq and yq
      shell: bash 
      run: |
        curl -LO https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-amd64
        curl -LO https://github.com/mikefarah/yq/releases/download/v4.45.1/yq_linux_amd64
        
        chmod +x jq
        chmod +x yq
        
        mv jq "${GITHUB_WORKSPACE}/tools/bin/jq"
        mv yq "${GITHUB_WORKSPACE}/tools/bin/yq"

    - name: Install Oracle Cloud CLI (oci)
      shell: bash 
      run: |
        curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh -o install.sh
        bash install.sh \
          --accept-all-defaults \
          --install-dir "${GITHUB_WORKSPACE}/tools" \
          --exec-dir "${GITHUB_WORKSPACE}/tools/bin" \
          --no-tty
        rm -rf install.sh
