name: Build Node.js App
on:
  workflow_call:
    inputs:
      build-properties-path:
        description: "Relative path to the build properties file (e.g., ./build/build-properties.json)"
        required: true
        type: string

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout caller
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }} 
          token: ${{ secrets.NICHOLAS_MONIZ_GITHUB_TOKEN }}
          path: ${{ github.event.repository.name }}

      - name: Checkout shared-pipeline
        uses: actions/checkout@v4
        with:
          repository: nicholas-moniz/shared-pipeline    
          token: ${{ secrets.NICHOLAS_MONIZ_GITHUB_TOKEN }}
          path: shared-pipeline
          ref: ${{ github.ref }}

      - name: Make all utility scripts executable
        run: chmod +x shared-pipeline/scripts/*.sh
        
      - name: Install npm modules
        working-directory: shared-pipeline
        run: npm ci

      - name: Set runtime environment variables
        uses: ./shared-pipeline/.github/actions/set-env-vars

      - name: Install tools
        uses: ./shared-pipeline/.github/actions/setup-tools
        
      - name: Cache Workspace
        uses: actions/cache/save@v4
        with:
          path: ${{ github.workspace }}
          key: ${{ runner.os }}-workspace-${{ github.run_id }}-${{ github.run_attempt }}
          
  next-job:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ github.workspace }}
          key: ${{ runner.os }}-workspace-${{ github.run_id }}-${{ github.run_attempt }}
