name: Build Node.js App
on:
  workflow_call:
    inputs:
      library-path:
        description: "Base path to shared actions"
        required: false
        type: string
        default: ./shared-pipeline/.github/actions

jobs:
  prepare:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash --rcfile ~/.bashrc -e -o pipefail -c
    steps:
      - name: Checkout caller
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }} 
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ github.event.repository.name }}
          fetch-depth: 1

      - name: Checkout shared-pipeline
        uses: actions/checkout@v4
        with:
          repository: nichoals-moniz/shared-pipeline    
          token: ${{ secrets.GITHUB_TOKEN }}
          path: shared-pipeline
          fetch-depth: 1
          ref: ${{ github.ref }}

      - name: Install npm modules
        working-directory: shared-pipeline
        run: npm ci

      - name: Install tools
        uses: ${{ inputs.library-path }}/setup-tools
      
      - name: Cache Workspace
        uses: actions/cache/save@v4
        with:
          path: ${{ github.workspace }}
          key: ${{ runner.os }}-workspace-${{ github.run_id }}
  next-job:
    runs-on: ubuntu-latest
    needs: prepare
    defaults:
      run:
        shell: bash --rcfile ~/.bashrc -e -o pipefail -c
    steps:
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.bashrc
            ${{ github.workspace }}
          key: ${{ runner.os }}-workspace-${{ github.run_id }}
      - name: Test
        run: echo "$PATH"
