name: Build Node.js App
on:
  workflow_call:
    inputs:
      build-properties-path:
        description: "Relative path to the build-properties.json file"
        required: true
        type: string

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout caller
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }} 
          token: ${{ secrets.NICHOLAS_MONIZ_GITHUB_TOKEN }}
          path: ${{ github.event.repository.name }}

      - name: Get reusable workflow ref from caller run
        id: get-shared-ref
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.NICHOLAS_MONIZ_GITHUB_TOKEN }}
          script: |
            const runId = context.runId;
            const repo = context.repo;
      
            // Fetch the run info
            const run = await github.rest.actions.getWorkflowRun({
              owner: repo.owner,
              repo: repo.repo,
              run_id: runId,
            });
      
            const workflows = run.data.referenced_workflows || [];
      
            const match = workflows.find(wf =>
              wf.path === "nicholas-moniz/shared-pipeline/.github/workflows/build-nodejs.yaml"
            );
      
            if (!match) {
              core.setFailed("Could not find matching reusable workflow reference.");
              return;
            }
      
            const ref = match.ref;
            core.info(`Found reusable workflow ref: ${ref}`);
            core.setOutput("ref", ref.replace("refs/heads/", ""));

      - name: Checkout shared-pipeline
        uses: actions/checkout@v4
        with:
          repository: nicholas-moniz/shared-pipeline    
          token: ${{ secrets.NICHOLAS_MONIZ_GITHUB_TOKEN }}
          path: shared-pipeline
          ref: ${{ steps.get-shared-ref.outputs.ref }}

      - name: Make all utility scripts executable
        working-directory: shared-pipeline/scripts
        run: chmod +x *.sh
        
      - name: Install npm modules
        working-directory: shared-pipeline
        run: npm ci

      - name: Set runtime environment variables
        uses: ./shared-pipeline/.github/actions/set-env-vars
        with:
          build-properties-path: ${{ inputs.build-properties-path }}

      - name: Install tools
        uses: ./shared-pipeline/.github/actions/setup-tools
        
      - name: Cache Workspace
        uses: actions/cache/save@v4
        with:
          path: ${{ github.workspace }}
          key: ${{ runner.os }}-workspace-${{ github.run_id }}-${{ github.run_attempt }}
          
  next-job:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ github.workspace }}
          key: ${{ runner.os }}-workspace-${{ github.run_id }}-${{ github.run_attempt }}
